// @vitest-environment jsdom
import type { ComponentProps } from "react";
import type { BoardExperienceScene } from "@/lib/learning/types";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/components/board-learning-content", () => ({ MarkedBoardText: ({ content }: { content: string }) => <p>{content}</p>, AnnotationNotes: () => null, BoardSourceTrail: ({ label }: { label: string }) => <p>{label}</p> }));
vi.mock("@/components/board-visual-boundary", () => ({ BoardVisualBoundary: () => <div>图示</div> }));
vi.mock("@/components/rich-learning-text", () => ({ RichLearningText: ({ text }: { text: string }) => <>{text}</> }));
import { BoardWorkspace } from "@/components/board-workspace";
const scene: BoardExperienceScene = { id: "s1", role: "reason", intent: "derive", content: "Δ=b²-4ac", title: "列出判别式", tone: "plain", medium: "text", purpose: "找到条件", actions: [{ id: "reveal", type: "reveal", targetId: "text" }], elements: [{ id: "text", type: "text", text: "Δ=b²-4ac" }], evidence: "两个实数根", why: "因为要判断根", selfCheck: "复述判别式", sourceMessageIds: ["m"] };
const props: ComponentProps<typeof BoardWorkspace> = { document: { version: 1, key: "board", legacyWorkspaceKey: "legacy", title: "判别式", learningGoal: "判断根", nodes: [{ id: "n1", sceneIndex: 0, title: "判别式", intent: "derive", prerequisiteIds: [], dependentIds: [], sourceMessageIds: ["m"] }] }, experience: { version: 1, key: "board", legacyWorkspaceKey: "legacy", title: "判别式", learningGoal: "判断根", layout: "steps", returnLabel: "返回", scenes: [scene], subject: "math", annotations: [] }, sourceMessages: [{ id: "m", role: "assistant", text: "原讲解" }], state: { version: 1, documentKey: "board", mode: "overview", activeNodeId: "n1", nodes: [{ nodeId: "n1", revealed: true }] }, onChange: vi.fn() };
describe("BoardWorkspace", () => { beforeEach(() => { Object.defineProperty(globalThis, "requestAnimationFrame", { configurable: true, value: (fn: FrameRequestCallback) => { fn(0); return 1; } }); Object.defineProperty(globalThis, "cancelAnimationFrame", { configurable: true, value: vi.fn() }); }); afterEach(cleanup);
 it("呈现教学内容并能切换到主动回忆与恢复原板书", () => { const change = vi.fn(); const { rerender } = render(<div className="board-scroll"><BoardWorkspace {...props} onChange={change}/></div>); expect(screen.getByText("Δ=b²-4ac")).not.toBeNull(); fireEvent.click(screen.getByRole("button", { name: "遮住后复述" })); expect(change).toHaveBeenCalledWith(expect.objectContaining({ mode: "recall", activeNodeId: "n1" })); rerender(<div className="board-scroll"><BoardWorkspace {...props} state={{ ...props.state, mode: "recall", activeNodeId: "n1", nodes: [{ nodeId: "n1", revealed: false }] }} onChange={change}/></div>); expect(screen.getByText("主动回忆")).not.toBeNull(); fireEvent.click(screen.getByRole("button", { name: "查看原板书" })); expect(change).toHaveBeenCalledWith(expect.objectContaining({ mode: "overview" })); });
});
