/** Interface copy only. Never pass problem, answer, or generated lesson text here. */
export type UiLocale = "zh" | "en";
export const UI_LOCALE_KEY = "education-ui-locale";
export const englishUiCopy: Record<string, string> = {
  "问这句": "Ask about this", "哪段没懂？轻点正文，选中后问小逗号。": "Something unclear? Tap a paragraph to select it and ask Comma.", "关闭长按提问提示": "Dismiss selection hint",
  "小实验": "Mini-experiment", "知识图谱": "Knowledge map", "对话导出": "Conversation export", "划词提问": "Selection questions",
  "{feature}暂时不可用": "{feature} is temporarily unavailable",
  "正在加载{feature}…": "Loading {feature}…",
  "重试{feature}": "Retry {feature}",
  "不影响当前解题，可以继续讲解或稍后重试。": "Your current lesson is unaffected. Continue learning or retry later.",
  "长方形知识小实验": "Rectangle mini-experiment",
  "换个方式理解": "Explore another way",
  "拖一拖，看看周长和面积": "Explore perimeter and area",
  "独立知识实验 · 不是原题配图，数值不用于原题作答": "Independent example · Not the original diagram or values for your answer",
  "保持周长不变": "Keep perimeter fixed",
  "重新观察": "Start again",
  "先改变一条边，观察边界和铺满图形的小方格。": "Change a side. Watch the boundary and the squares inside.",
  "周长已固定。改变长，看看宽和面积怎样变化。": "Perimeter is fixed. Change length and watch width and area.",
  "当前整数范围内只有这一种形状。解除固定或重新观察，即可继续。": "Only one shape fits this whole-number range. Unlock or start again to explore.",
  "实验长方形：长 {length} 厘米，宽 {width} 厘米": "Example rectangle: length {length} cm, width {width} cm",
  "每个小方格是 1 平方厘米 · 虚线为本轮起点": "Each square is 1 cm² · Dashed line: starting shape",
  "长": "Length", "宽": "Width",
  "实验长方形的长": "Example rectangle length",
  "实验长方形的宽": "Example rectangle width",
  "随长自动变化": "Adjusts with length",
  "周长 · 边界一圈": "Perimeter · Boundary",
  "面积 · 方格总数": "Area · Squares inside",
  "本轮起点：{value}": "Starting value: {value}",
  "你发现了什么？": "What did you notice?",
  "可以写下发现或疑问，也可以直接问这个变化的原因…": "Share an observation or question, or ask why it changed…",
  "会带上本轮前后的数值，接着原题讨论；不会提交为答案。": "Your before-and-after values will accompany your question, not be submitted as an answer.",
  "先拖动滑块改变图形，再带着观察回到原题。": "Move a slider first, then bring your observation back to the question.",
  "带着观察问小逗号": "Ask Comma about this",
  "收起实验，继续看题": "Close and return to the question",
  "原图在当前浏览器不可用，以下是已识别的题目内容。": "The original image is unavailable in this browser. Here is the recognized question.",
  "原图在当前浏览器不可用，题干尚未识别完成。": "The original image is unavailable in this browser, and recognition is incomplete.",
  "已识别的配图信息": "Recognized diagram information",
  "照片中的已有作答": "Existing work in the photo",
  "原图未能保存在此浏览器；刷新后可查看已识别题干。": "The original image could not be saved in this browser. Recognized text remains available after reloading.",
  "原图暂时无法恢复，可展开原题查看已识别题干。": "The original image could not be restored. Expand the original question to see the recognized text.",
  "旧原图未能从本机清理，可在浏览器设置中清除网站数据。": "The old image could not be removed. You can clear site data in your browser settings.",
  "查看原题": "View original question",
  "收起原题": "Hide original question",
  "理解这题，先看这一点": "One idea to help you understand",
  "摘自本题讲解": "From this question’s explanation",
  "正在找出核心知识…": "Finding the key concept…",
  "已显示的知识仍可查看": "You can still explore the concepts shown",
  "看看它们怎样关联": "Explore how they connect",
  "展开本题知识图谱": "Expand this concept map",
  "读懂题目后，知识点会在这里展开": "Concepts appear here once the question is understood",
  "查看知识点：{title}": "Explore concept: {title}",
  "请补充题目配图": "Add the question diagram",
  "文字已读懂，还需要补一张图": "Text read. One more image is needed.",
  "以下条件没有拍到，补齐后才能准确讲解。已识别的文字会保留。": "These details are missing from the photo. Add them for an accurate explanation. The recognized text is saved.",
  "补拍或上传完整题目和配图": "Photograph or upload the full question and diagram",
  "查看已识别文字": "View recognized text",
  "题目已经读懂，先从核心思路开始": "Question ready. Start with the main idea.", "先抓住这道题的核心": "Start with the main idea", "完整讲解已收起，现在确认一个关键步骤": "Explanation hidden. Check a key step.", "本次讲解已结束，当前记录为：基本理解，尚未验证独立掌握": "Review complete. Independent understanding is not yet verified.",
  "继续验证：遮住讲解，重做同一道原题": "Hide the explanation and try the original question again", "接下来可以独立试做原题，有疑问也可以继续提问": "Try the original question on your own, or keep asking", "现在你来独立完成原题": "Now solve the original question on your own",
  "下一步聚焦：{title}": "Next focus: {title}", "已经定位到卡点：{title}": "Where you got stuck: {title}", "继续往基础处找：{title}": "Back to the basics: {title}", "这一点已通过，继续：{title}": "Concept checked. Next: {title}",
  "先把完整思路看清楚": "Read through the full approach", "完整讲解已展示，阅读后再进入关键步骤检查": "Read the explanation, then check a key step", "基础已经走通，现在回到原题": "Basics covered. Back to the original question.", "关键步骤已经理解，现在选择怎样独立验证": "Key steps understood. Choose how to check them independently.",
  "这道题已经能独立完成": "You can solve this question independently", "可选强化 · AI 生成同知识点题": "Optional practice · AI-generated question", "已经独立完成一道同知识点题": "You solved a similar question independently", "这是刚才的原题。讲解已收起，请按自己的思路完成": "The original question, with the explanation hidden. Try it on your own.", "现在不看讲解，自己完成原题": "Solve the original question without the explanation",
  "学不可以已。": "Learning never stops.", "不积跬步，无以至千里。": "A long journey is built from small steps.", "锲而不舍，金石可镂。": "With persistence, even stone can be carved.", "知之为知之，不知为不知。": "Know what you know, and admit what you don’t.",
  "学而不思则罔，思而不学则殆。": "Learning needs reflection; reflection needs learning.", "温故而知新，可以为师矣。": "Revisit what you know to discover something new.", "敏而好学，不耻下问。": "Be eager to learn and never ashamed to ask.", "博学而笃志，切问而近思。": "Learn widely, stay focused, ask carefully and reflect.",
  "学然后知不足。": "Learning reveals what we still need to understand.", "玉不琢，不成器；人不学，不知道。": "Jade needs shaping; understanding needs learning.", "独学而无友，则孤陋而寡闻。": "Learning with others broadens what we know.", "善问者如攻坚木，先其易者，后其节目。": "A good question starts with the easy part, then tackles the knots.",
  "博学之，审问之，慎思之，明辨之，笃行之。": "Learn, question, reflect, distinguish and put it into practice.", "为学患无疑，疑则有进。": "Questions are where learning moves forward.", "纸上得来终觉浅，绝知此事要躬行。": "To truly understand, put what you read into practice.", "旧书不厌百回读，熟读深思子自知。": "Reading again and thinking deeply brings understanding.",
  "博观而约取，厚积而薄发。": "Learn widely, choose carefully and build understanding over time.", "问渠那得清如许？为有源头活水来。": "Fresh learning keeps understanding clear, like a flowing spring.", "读书之法，在循序而渐进，熟读而精思。": "Learn step by step, read closely and think deeply.", "读书破万卷，下笔如有神。": "Reading widely gives life to your writing.",
  "千淘万漉虽辛苦，吹尽狂沙始到金。": "Finding gold takes patience and repeated effort.", "山重水复疑无路，柳暗花明又一村。": "When the path seems blocked, a new way may appear.", "路漫漫其修远兮，吾将上下而求索。": "The road is long; keep exploring and asking.", "千里之行，始于足下。": "A long journey begins with a single step.",
  "《荀子·劝学》": "Xunzi · Encouraging Learning", "《论语·为政》": "Analects · On Government", "《论语·公冶长》": "Analects · Gongye Chang", "《论语·子张》": "Analects · Zizhang", "《礼记·学记》": "Book of Rites · On Learning", "《礼记·中庸》": "Book of Rites · The Mean", "陆九渊《语录》": "Lu Jiuyuan · Recorded Sayings", "陆游《冬夜读书示子聿》": "Lu You · Reading on a Winter Night", "苏轼《送安惇秀才失解西归》": "Su Shi · Farewell to An Dun", "苏轼《稼说送张琥》": "Su Shi · On Cultivation", "朱熹《观书有感·其一》": "Zhu Xi · Reflections on Reading I", "朱熹《读书之要》": "Zhu Xi · Essentials of Reading", "杜甫《奉赠韦左丞丈二十二韵》": "Du Fu · A Poem for Wei Zuo Cheng", "刘禹锡《浪淘沙·其八》": "Liu Yuxi · Waves Washing the Sand VIII", "陆游《游山西村》": "Lu You · Visiting a Mountain Village", "屈原《离骚》": "Qu Yuan · Li Sao", "《道德经·第六十四章》": "Tao Te Ching · Chapter 64",
  "正在整理当前这一步的关键填空": "Preparing the key blank for this step", "正在定位这一步真正缺少的基础": "Finding the missing foundation", "正在确认同类练习需要覆盖的知识点": "Choosing concepts for your practice", "正在生成并核对同知识点练习": "Creating and checking a similar question", "只完成这一个关键空": "Fill in just this key blank", "查看这个空的答案": "Show this answer",
  "等待超时，当前学习任务已保留，可以直接重试。": "The request timed out. Your task is saved — you can retry.",
  "「": "“", "」": "”", "这一段听懂了吗？": "Does this part make sense?",
  "关键步骤已经理解。接下来怎么确认？": "How would you like to check your understanding?", "先说清楚一个关键步骤": "Explain one key step", "这一步的解题方向理解了吗？": "Does this approach make sense?",
  "接下来要用到“{title}”": "Next, we’ll use “{title}”", "用一道小题确认“{title}”": "Check “{title}” with a short question", "“{title}”现在清楚一些了吗？": "Is “{title}” clearer now?", "更基础的“{title}”听懂了吗？": "Does the basic idea of “{title}” make sense?", "“{title}”听懂了吗？": "Does “{title}” make sense?",
  "可以继续追问当前步骤、查看完整讲解，或请老师一起确认这个卡点": "Keep asking, read the full explanation, or ask a teacher for help.", "可以继续追问当前知识点、查看完整讲解，或请老师一起确认": "Keep asking about this concept, read the explanation, or ask a teacher.",
  "换一种讲法后，清楚一些了吗？": "Did that explanation make it clearer?", "换个例子后，清楚一些了吗？": "Did the new example help?", "这个最小知识点仍然卡住了，可以继续提问或请老师一起看": "Still stuck on this basic idea? Keep asking or ask a teacher to help.", "这个基础点仍未通过检查，可以继续问或请老师一起看": "This concept needs more practice. Keep asking or ask a teacher to help.",
  "这一步已完成，继续往下学": "Step complete. Let’s continue.", "找到刚才卡住的位置了吗？": "Have you found where you got stuck?", "再想一想这个关键步骤": "Think about this key step again", "找到刚才出错的那一步了吗？": "Have you found the step that went wrong?", "再想一次": "Try once more",
  "需要先理解": "Understand first", "继续": "Continue", "没懂": "I need help",
  "收起{title}的基础知识": "Hide prerequisites for {title}", "展开{title}的基础知识": "Show prerequisites for {title}", "{title}的知识说明": "About {title}",
  "只保留你的作答": "Crop to your answer", "只保留想问的位置": "Crop to the part you want to ask about", "拖动框移动，拖四角精确调整": "Move the frame or drag a corner to resize", "使用这份作答": "Use this answer", "发送这张图片": "Send this image",
  "写下题目、公式或画出图形": "Write a question, formula or diagram", "围绕当前题目写下步骤或画出疑问": "Write your steps or draw what is unclear", "识别这道题": "Read this question", "提交作答": "Submit answer", "发送提问": "Send question", "写题目、公式或画图都可以，AI 会先识别再开始讲解": "Write or draw your question. AI will read it before explaining.",
  "重新分析": "Analyze again", "操作失败，请重试": "Could not complete the action. Please retry.", "AI 服务暂不可用，请稍后刷新重试。": "AI is unavailable. Please refresh and try again later.",
  "上次请求未完成，可以在消息旁重试。": "The last request was incomplete. Retry beside the message.", "当前浏览器无法保存进度；关闭页面后记录会丢失。": "This browser cannot save progress. Closing the page will lose your record.",
  "AI 返回内容格式异常，当前学习位置已保留，请重试这一步。": "The AI returned an invalid response. Your progress is saved. Please retry this step.",
  "推理强度已切换为「轻度」": "Reasoning set to Light", "推理强度已切换为「中」": "Reasoning set to Medium", "推理强度已切换为「高」": "Reasoning set to High",
  "同类练习暂时没有生成成功，当前学习进度已保留。可以继续提问、选择其他操作，或再次点击生成练习。": "The practice question wasn’t generated. Your progress is saved. Keep asking, choose another action, or retry.",
  "这次整理超时了，已显示的知识点仍可查看。": "Generation timed out. You can still explore the concepts shown.", "浏览器暂时无法保存布局，本次仍可自由调整。": "This browser cannot save the layout. You can still arrange it for this visit.",
  "模型响应超时，请稍后重试同一模型": "The model timed out. Please retry shortly.", "完整讲解因输出长度限制被截断，请重试当前操作": "The explanation reached the output limit. Please retry this step.",
  "没有识别清楚，请重写或用键盘填写": "Couldn’t read that. Rewrite it or use the keyboard.", "这一步只需要简短填写，请只写空格里的内容。": "Keep it short — write only the missing part.", "识别可能有误，请核对或修改。": "Please check the recognized text and edit if needed.", "已回填，可以修改或显示答案对照。": "Filled in. You can edit or compare with the answer.", "识别失败，手写内容已保留，请重试。": "Couldn’t read the writing. It is still here — please retry.",
  "照片读取失败，请重新选择。 ": "Could not load the photo. Please choose it again.", "图片旋转失败，请重试。": "Could not rotate the image. Please retry.", "图片处理失败，请重新选择。 ": "Could not process the image. Please choose it again.", "当前浏览器无法旋转图片": "This browser cannot rotate the image", "图片太大，无法旋转，请换一张较小的图片。": "The image is too large to rotate. Choose a smaller one.", "当前浏览器无法处理图片": "This browser cannot process the image", "图片压缩失败": "Could not compress the image", "图片格式无法读取，请换一张照片": "Unsupported image format. Choose another photo.",
  "图片或字体准备超时，请关闭预览后重试。": "Images or fonts timed out. Close the preview and retry.", "部分本地图片已失效，PDF 会保留其位置与说明；文字内容不受影响。": "Some local images are unavailable. Their captions remain in the PDF; text is unaffected.", "当前浏览器不支持打印，请用 Chrome、Edge 或 Safari 打开后导出。": "Printing is unavailable. Open in Chrome, Edge or Safari to export.", "未能打开保存窗口，请使用浏览器菜单中的“打印”，并选择保存为 PDF。": "Could not open the save dialog. Use Print in the browser menu, then Save as PDF.",
  "正在回答你选中的问题": "Answering your selected question", "正在回答你刚才的问题": "Answering your question", "正在看你标出的疑问": "Looking at the part you marked", "正在判断你的思路": "Checking your approach", "正在阅读你的作答": "Reading your answer", "正在重新打开原题作答": "Reopening the original question", "正在生成同知识点新题": "Creating a similar question", "正在准备关键步骤回忆": "Preparing a key-step check", "正在换一种更容易理解的讲法": "Finding a clearer explanation", "正在组织完整讲解": "Preparing the full explanation", "正在收起讲解并准备关键步骤检查": "Preparing a check with the explanation hidden", "正在继续讲解": "Continuing the explanation", "正在补基础": "Revisiting the basics",
  "专注作业": "Comma",
  "专注作业 持续理解": "Comma · Learn with understanding",
  "小逗号": "Comma",
  "Hey，小逗号陪你一起解题。": "Hey, solve it together with Comma.",
  "小逗号，点一下和它打招呼": "Tap Comma to say hello",
  "和小逗号打招呼": "Say hello to Comma",
  "陪你一起解题。": "Let’s solve it together.",
  "已累计解题 {count} 次": "{count} questions started",
  "统计暂不可用": "Statistics temporarily unavailable",
  "正在读取解题次数": "Loading question count",
  "小学": "Primary", "初中": "Middle", "高中": "High",
  "模型识别为{grade}题": "{grade}",
  "导出 PDF": "Export PDF", "导出当前全部对话": "Export this conversation", "开始新题": "New question",
  "对话内容": "Conversation", "再次查看刚才的板书": "Reopen the board", "不改变当前任务": "Keep the current task",
  "正在引用的文字": "Selected passage", "针对这段文字提问": "Ask about this passage", "取消引用": "Remove quote", "取消": "Cancel",
  "拍照发题": "Take a photo", "从相册选择题目": "Choose a photo", "白板写题": "Write a question",
  "当前环节": "Current step", "返回作答": "Back to answer", "改为提问": "Ask a question", "输入方式": "Input options",
  "白板作答": "Write an answer", "白板提问": "Write a question", "拍照作答": "Photograph your answer", "拍照提问": "Photograph your question",
  "打开白板作答": "Open answer canvas", "打开白板提问": "Open question canvas",
  "请先重试刚才未完成的步骤": "Retry the unfinished step first",
  "想问这段文字的什么？": "What would you like to ask about this?", "请点击上方选项作答": "Choose an answer above",
  "询问当前步骤": "Ask about this step", "输入你的答案": "Enter your answer", "输入题目或问题": "Enter a question",
  "发送问题": "Send question", "提交答案": "Submit answer", "发送": "Send",
  "AI 服务正在准备": "Getting the AI ready", "输入一道题目…": "Type a question…", "继续问这道题…": "Ask more about this question…",
  "推理强度": "Reasoning", "轻度": "Light", "中": "Medium", "高": "High", "轻度推理": "Light reasoning", "中推理": "Medium reasoning", "高推理": "High reasoning",
  "轻度推理尚未配置": "Light reasoning unavailable", "中推理尚未配置": "Medium reasoning unavailable", "高推理尚未配置": "High reasoning unavailable",
  "请选择图片文件": "Please choose an image", "图片不能超过 20MB": "Images must be under 20 MB",
  "选中文字过长，请将引用控制在 12000 字以内。": "Please select fewer than 12,000 characters.",
  "有新讲解 · 猜你想问 ↓": "New explanation · More questions ↓", "下面有猜你想问 ↓": "Suggested questions below ↓", "有新讲解 ↓": "New explanation ↓",
  "正在补回缺失的基础": "Revisiting the basics", "理解后会自动回到刚才的原题步骤": "You’ll return to the original question after this.",
  "完整讲解未完成": "Explanation incomplete", "完整讲解已收起": "Explanation hidden", "接下来只保留学习任务，避免答案继续影响独立思考。": "Try the task on your own with the explanation hidden.",
  "引用 ·": "Quoted ·", "关于「": "About “", "学生发送的题目": "Student’s question", "关联 ·": "Related ·",
  "本条处理未完成": "This step is incomplete", "本条处理未完成，请重新发送问题或继续当前步骤。": "This step is incomplete. Resend your question or continue the current step.",
  "重试这条消息": "Retry this message", "重新请求，不刷新页面": "Retry without refreshing", "重试中": "Retrying", "重试": "Retry", "重试这一步": "Retry this step", "重新识别": "Read again", "请重试": "Please retry",
  "猜你想问": "You might ask", "当前学习任务": "Current learning task", "轮到你了": "Your turn",
  "同一道原题": "Original question", "同类练习": "Similar practice", "关键步骤检查": "Key-step check", "理解检查": "Understanding check",
  "还没懂，再讲一下": "Explain that again", "请在下方输入你的答案并发送。": "Type your answer below and send it.",
  "这一步我来做": "Let me try", "可以在下方继续描述哪里不懂。": "Tell us what is unclear below.", "辅助讲解": "More help",
  "懂了，继续": "Got it, continue", "我来试试": "Let me try", "这一步没懂": "I need help", "看完整讲解": "Full explanation", "用板书讲清楚": "Show on the board",
  "核心思路听懂了吗？": "Does the main idea make sense?", "完整讲解已经准备好": "The full explanation is ready", "我看完了，收起讲解": "Finished reading, hide it", "先结束，稍后再练": "Finish now, practice later",
  "答案选项": "Answer choices", "选择一个答案": "Choose an answer",
  "识别结果需要你确认": "Please check the recognized question", "题目文字": "Question text", "这道题需要看图吗？": "Is the diagram part of this question?", "解题需要": "Required", "辅助理解": "Helpful", "与题无关": "Unrelated",
  "图中信息": "Diagram details", "每行一条，只保留属于这道题、且能从图中直接看到的条件。": "One fact per line. Include only facts visible in the diagram for this question.",
  "这道题依赖配图，请补全图中条件或重新拍摄。": "This question needs its diagram. Add the missing facts or take another photo.", "确认题目，开始讲解": "Confirm and start",
  "下一步正在准备": "Preparing the next step", "即将出现": "Coming up", "接下来会轮到你": "Your turn is coming", "正在把刚才的内容整理成下一步互动": "Preparing a task based on what you just learned",
  "已验证掌握": "Understanding verified", "你已经独立解决了这道原题": "You solved the original question on your own", "你已经独立解决了一道同知识点题": "You solved a similar question on your own",
  "原题独立作答已经通过。": "Your independent answer passed.", "换了题目后仍能使用同一关键方法。": "You applied the same method to a new question.",
  "这次还补过 {count} 个基础节点。": "You also revisited {count} foundational concepts.", "还可以继续追问，不会丢失本题上下文。": "Keep asking — this question stays in context.",
  "再练一道同类题": "Practice another", "同类题由 AI 生成，不冒充真题或高频题": "Practice questions are AI-generated, not past exam questions.",
  "已学习 · 尚未验证掌握": "Reviewed · Practice still needed", "关键步骤已经理解": "You understand the key steps",
  "你看过完整讲解，也说清了关键关系；但还没有独立做对一道题，因此暂不标记为“已掌握”。": "You reviewed the explanation and explained the key relationship. Solve a question independently to verify your understanding.",
  "遮住讲解，重做原题": "Hide explanation and retry", "换一道同知识点题": "Try a similar question",
  "解决你对当前步骤的疑问": "Ask about this step", "具体说说你卡在哪一步…": "Which step are you stuck on?",
  "确认你是否理解核心思路": "Check the main idea", "确认新的讲法是否解决了卡点": "Did this explanation help?", "确认你是否理解当前这一步": "Check this step",
  "懂了、没懂，或直接问…": "Got it, need help, or ask…", "试着填写这一步，或显示答案对照": "Fill in the step or compare answers", "有疑问可以在这里问…": "Ask a question here…",
  "用一道小题检验当前知识点": "Check your understanding", "写下答案，也可以补充你的思路…": "Write your answer and how you got it…",
  "完整阅读解题过程，找出仍不清楚的步骤": "Read through and find any unclear steps", "可以继续问讲解中没看懂的步骤…": "Ask about any unclear step…",
  "用自己的话说清一个关键步骤": "Explain a key step in your own words", "写下你理解的关键步骤…": "Explain the key step…",
  "选择一种方式验证是否真正掌握": "Choose how to check your understanding", "也可以告诉我你想怎样继续…": "How would you like to continue?",
  "独立完成原题，验证是否真正掌握": "Solve the original question independently", "写下答案和关键步骤…": "Write your answer and key steps…",
  "完成同类题，验证方法能否迁移": "Apply the method to a similar question", "写下这道同类题的答案和思路…": "Write your answer and approach…",
  "说清具体卡点，找到下一种讲法": "Tell us where you need help", "告诉我具体卡在哪里…": "Where exactly are you stuck?",
  "正在复制…": "Copying…", "已复制文本": "Text copied", "已复制纯文本": "Plain text copied", "复制讲解": "Copy explanation", "复制文本": "Copy text", "复制失败：{error}": "Could not copy: {error}",
  "正在准备": "Preparing", "正在输出": "Writing", "输出完成": "Finished", "还在继续": "Still writing",
  "小逗号正在思考": "Comma is thinking", "学习寄语": "A thought on learning",
  "正在读懂这道题": "Reading your question", "识别题目条件，整理问题要求。": "Identifying the facts and what you need to find.",
  "正在梳理解题思路": "Finding an approach", "从题目条件出发，找到讲解的切入点。": "Using the given facts to find a starting point.",
  "正在整理你的问题": "Thinking about your question", "结合当前题目，整理清楚再讲给你。": "Putting together a clear explanation for this question.",
  "本题知识脉络": "Knowledge connections", "本题知识图谱": "Knowledge map", "查看完整知识图谱": "Explore the knowledge map", "让知识连起来": "Connect what you learn",
  "生成暂时中断": "Generation paused", "已全部生成": "All concepts ready", "正在确认知识关系": "Checking connections", "知识正在连起来": "Connecting concepts", "正在梳理本题知识": "Mapping the concepts",
  "从本题核心开始": "Starting with the main idea", "知识点生成进度": "Concept progress", "正在确定知识清单": "Planning the concepts", "重试生成": "Retry generation",
  "正在梳理关联知识": "Connecting related concepts", "核心知识已识别，正在梳理关联": "Core concept identified. Mapping its connections.",
  "正在展开关联知识": "Expanding related concepts", "知识点会陆续出现": "More concepts will appear as they are ready", "图谱还在展开": "Your map is still growing",
  "点击知识点，看看它在本题中怎么用": "Tap a concept to see how it applies", "清单已确定，正在整理根节点": "Plan ready, preparing the main idea", "画布已就绪，知识点会陆续出现": "The canvas is ready. Concepts will appear as they arrive.",
  " / {total} 个知识点": " / {total} concepts", "已生成 {count} / {total} 个知识点": "{count} / {total} concepts ready", "，生成中断": ", generation paused", "已生成 {count} / {total} · {latest}": "Ready {count} / {total} · {latest}",
  "正在整理本题核心": "Preparing the main idea", "正在补充知识点": "Adding a concept", "本题核心": "Main idea", "下一个知识点": "Next concept", "等待继续整理": "Waiting to resume", "正在连接知识…": "Connecting ideas…", "关联知识": "Related concept",
  "收起基础": "Hide basics", "展开 {count} 个基础": "Show {count} basics", "点击了解它在本题的作用": "Tap to see how it helps", "返回对话": "Back to conversation", "返回": "Back",
  "知识分支已更新，可点击“查看全图”查看完整范围。": "Branches updated. Choose Fit map to see them all.", "节点位置已保存": "Position saved", "已恢复整齐布局，知识关系没有改变。": "Layout reset. Connections are unchanged.",
  "可拖拽的知识图谱": "Draggable knowledge map", "图谱视图工具": "Map controls", "缩小图谱": "Zoom out", "放大图谱": "Zoom in", "查看全图": "Fit map", "整理": "Tidy up",
  "拖节点排布 · 拖空白移动 · 双指缩放": "Drag nodes to arrange · Drag canvas to move · Pinch to zoom",
  "知识卡片": "Concept card", "关闭知识卡片": "Close concept card", "对应本题条件": "Given in this question",
  "布局保存在本机 · 浏览图谱不改变学习进度": "Layout saved locally · Exploring won’t change your progress", "AI 整理，请结合原题理解": "AI-generated. Check against the original question.",
  "它是什么": "What it means", "本题怎么用": "How it applies", "补充说明暂未加载，仍可浏览图谱。": "Details unavailable. You can still explore the map.", "重试说明": "Retry details",
  "正在整理知识讲解": "Preparing the concept explanation", "知识讲解已就绪": "Concept explanation ready", "等待重试补充": "Waiting for a retry",
  "导出图片": "Save image", "导出全部已生成知识点、连线和关系标签": "Save all generated concepts, lines and relationship labels", "导出中…": "Saving…", "图片已生成 ·": "Image ready ·", "再次下载": "Download again",
  "图片导出失败，请重试": "Could not export the image. Please retry.", "图片导出超时，请重试": "Image export timed out. Please retry.", "共 {count} 个知识点": "{count} concepts", "生成中快照 · 已生成 {count} 个知识点": "Snapshot · {count} concepts ready", " · 本图仅包含导出时已生成的内容": " · Includes only content ready at export time",
  "完整对话导出内容": "Conversation export", "专注作业 / 学习记录": "Comma / Learning record", "把思路，留在纸上。": "Keep your thinking on paper.", "原题": "Original question", "已有作答": "Previous work", "完整对话": "Full conversation",
  "导出于 {date} · {count} 条记录": "Exported {date} · {count} entries", "我的提问与作答": "My questions and answers", "讲解": "Explanation", "学习进度": "Learning progress", " · 板书记录": " · Board notes",
  "本条记录中的题目或作答图片": "Question or answer image", "题目 / 作答图片": "Question / answer image", "此条仍在生成，记录截至导出时已收到的内容。": "Still generating. Includes content received at export time.", "此条处理未完成，以上为已收到的内容。": "Incomplete. Content received so far is shown above.", "（关联：": "(Related: ",
  "以上为本浏览器当前会话的本地记录，包含已收起的讲解；不包含未发送草稿。图片如已因刷新失效，则无法恢复。AI 讲解请结合题目核对。": "Local record of this session, including hidden explanations but not unsent drafts. Images lost on refresh cannot be restored. Check AI explanations against the question.",
  "本地保存 · 无需上传": "Saved locally · No upload", "导出对话 PDF": "Export conversation", "关闭导出预览": "Close export preview",
  "点击保存后，在打印窗口选择“另存为 PDF”。建议 A4 纵向；关闭浏览器页眉和页脚。": "Select Save as PDF in the print dialog. Use A4 portrait and turn off browser headers and footers.",
  "保存为 PDF": "Save as PDF", "正在准备图片与公式…": "Preparing images and formulas…",
  "只保留一道题": "Crop to one question", "拖动框移动，拖四角调整范围": "Move the frame or drag a corner to resize", "裁剪并识别": "Crop and read", "重置裁剪区域": "Reset crop", "待裁剪的作业照片": "Question photo to crop", "正在读取照片…": "Loading photo…",
  "拖动左上角调整裁剪范围": "Resize from top left", "拖动右上角调整裁剪范围": "Resize from top right", "拖动左下角调整裁剪范围": "Resize from bottom left", "拖动右下角调整裁剪范围": "Resize from bottom right",
  "放大查看": "Preview", "旋转90°": "Rotate 90°", "正在处理图片…": "Processing image…", "放大查看图片": "Image preview", "双指缩放，单指移动": "Pinch to zoom, drag to move", "返回裁剪": "Back to crop", "放大预览的作业照片": "Question photo preview", "缩小": "Zoom out", "放大": "Zoom in", "恢复适应屏幕": "Fit to screen",
  "正在识别": "Reading", "画笔": "Pen", "橡皮": "Eraser", "撤销": "Undo", "重做": "Redo", "清空": "Clear",
  "写步骤、公式或画辅助线都可以，AI 会结合当前题目阅读": "Write steps, formulas or a diagram. AI will read them with this question.",
  "白板还没有可发送的内容": "Write something before sending", "白板导出失败，请重试": "Could not export your writing. Please retry.",
  "当前步骤填空": "Fill in this step", "修改这个空的答案": "Edit this answer", "点击填写这个空": "Tap to fill in", "点击填写": "Tap to fill in", "只填这一个空，不用重做整题。点击空格可以手写。": "Fill in just this blank. Tap it to write by hand.",
  "收起键盘修改": "Hide keyboard input", "也可以用键盘填写 / 修改": "Type or edit with the keyboard", "修改填空答案": "Edit the blank", "看懂了，继续": "Got it, continue", "显示答案": "Show answer", "给我一点提示": "Give me a hint", "填写这一个空": "Fill in this blank", "识别并填入": "Read and fill in", "只写空格里的内容；回填后还可以修改，不会自动提交。": "Write only the missing part. You can edit it before submitting.",
  "拖动调整选区起点": "Drag selection start", "拖动调整选区终点": "Drag selection end", "针对选中文字问一问": "Ask about selected text", "问一问": "Ask",
};

// Some fixed controls arrive from the API with a concept name interpolated.
// Match only catalogued UI templates; captured names remain in their original language.
const uiTemplates = Object.entries(englishUiCopy).filter(([source]) => /\{\w+\}/.test(source)).map(([source, english]) => {
  const keys = Array.from(source.matchAll(/\{(\w+)\}/g), match => match[1]);
  const pattern = source.split(/\{\w+\}/).map(part => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("([\\s\\S]+?)");
  return { regex: new RegExp(`^${pattern}$`), keys, english };
});

export function translateUi(locale: UiLocale, source: string, values?: Record<string, string | number>): string {
  const translated = Object.hasOwn(englishUiCopy, source) ? englishUiCopy[source] : undefined;
  if (locale === "en" && !values && translated === undefined) {
    for (const { regex, keys, english } of uiTemplates) {
      const match = regex.exec(source);
      if (match) return english.replace(/\{(\w+)\}/g, (token, key: string) => match[keys.indexOf(key) + 1] ?? token);
    }
  }
  const template = locale === "en" ? translated ?? source : source;
  return values ? template.replace(/\{(\w+)\}/g, (match, key: string) => Object.hasOwn(values, key) ? String(values[key]) : match) : template;
}
